export const GET_POPULAR_MOVIES = "GET_POPULAR_MOVIES";

export const SEARCH_MOVIES = "SEARCH_MOVIES";

export const LOAD_MORE_MOVIES = "LOAD_MORE_MOVIES";

export const CLEAR_MOVIES = "CLEAR_MOVIES";

export const SHOW_LOADING_SPINNER = "SHOW_LOADING_SPINNER";
