export const GET_POPULAR_MOVIES = "GET_POPULAR_MOVIES";

export const SEARCH_MOVIES = "SEARCH_MOVIES";

export const LOAD_MORE_MOVIES = "LOAD_MORE_MOVIES";

export const CLEAR_MOVIES = "CLEAR_MOVIES";

export const SHOW_LOADING_SPINNER = "SHOW_LOADING_SPINNER";

export const MOVIES_PERSISTED_STATE = "MOVIES_PERSISTED_STATE";

export const GET_MOVIE = "GET_MOVIE";

export const MOVIE_CREW = "MOVIE_CREW";

export const CLEAR_MOVIE = "CLEAR_MOVIE";

export const MOVIE_PERSISTED_STATE = "MOVIE_PERSISTED_STATE";
